In [2]:
import numpy as np

In [3]:
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result
to_square = range(10000)
%timeit squares(to_square)

1.12 ms ± 19.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
array_to_square = np.arange(0,10000)
%timeit array_to_square ** 2

8.81 µs ± 63.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [8]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [12]:
x.ndim?

In [18]:
x.shape

(6,)

In [19]:
x.size

6

In [22]:
x.itemsize

4

ndarray.ndim 数组轴的个数，在python中的世界中，轴的个数被称为秩
ndarray.shape数组的维度


In [23]:
x

array([1, 2, 3, 4, 5, 6])

In [24]:
type(x)

numpy.ndarray

In [25]:
x.shape

(6,)

In [26]:
x.ndim

1

In [27]:
x.size

6

In [28]:
x.dtype

dtype('int32')

In [36]:
x1 = np.array([1.0,2.2])
x1

array([1. , 2.2])

In [37]:
x1.dtype

dtype('float64')

In [38]:
x.data

In [39]:
y = np.array([[1,2,3,4,5],[6,7,8,9,10]])
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
y.ndim

2

In [41]:
y.size

10

In [42]:
y.shape

(2, 5)

In [43]:
x1 = np.array([1,2,3,4.0,5.0])
x1.dtype,x.dtype

(dtype('float64'), dtype('int32'))

In [44]:
x2 = np.array([1]*5)
x2

array([1, 1, 1, 1, 1])

In [45]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
range?

In [48]:
np.array(range(10,0,-1))

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [49]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [53]:
np.linspace?

In [63]:
x = np.array([1,2,3,4,5])

In [64]:
print(x)
print(x1)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [65]:
x + x1

array([ 2.,  4.,  6.,  8., 10.])

In [66]:
x2 = np.arange(0,12)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
x2 = x2.reshape(4,3)
x2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
np.size(x2)

12

In [69]:
np.size(x2,1)

3

In [70]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [72]:
np.empty((5,6))

array([[1.24634990e-311, 9.58487353e-322, 0.00000000e+000,
        0.00000000e+000, 1.24561153e-311, 5.02034658e+175],
       [9.60431342e-071, 2.77124819e-057, 1.95409639e+184,
        1.18996829e-047, 1.47763641e+248, 1.16096346e-028],
       [7.69165785e+218, 1.35617292e+248, 4.00402935e-057,
        7.78466580e-071, 7.11750830e-038, 9.30445104e+165],
       [4.30529555e-096, 6.32299154e+233, 6.48224638e+170,
        5.22411352e+257, 5.74020278e+180, 8.37174974e-144],
       [1.41529402e+161, 9.16651763e-072, 3.88580812e+097,
        2.74446931e-057, 3.75558860e+126, 1.24635332e-311]])

In [76]:
np.empty((2,2))

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [77]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.13430793e-321],
       [8.70018274e-313, 0.00000000e+000, 0.00000000e+000]])

In [79]:
np.empty((2,2,3))

array([[[1.24634020e-311, 2.47032823e-322, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 2.42336543e-057]],

       [[5.27749168e-091, 2.78857456e+179, 5.51233464e+169],
        [1.65821158e-076, 3.99910963e+252, 7.50011943e-067]]])

In [84]:
np.random.randint(0,10,3)

array([9, 3, 9])

In [85]:
np.random.random(10)

array([0.94790801, 0.44893966, 0.27971908, 0.43115741, 0.67816821,
       0.93417454, 0.79958779, 0.84854661, 0.45888503, 0.67459412])

In [86]:
x

array([1, 2, 3, 4, 5])

In [87]:
x[0],x[2]

(1, 3)

In [88]:
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [89]:
y[1,3]

9

In [90]:
y[0,4]

5

In [91]:
y[0,]

array([1, 2, 3, 4, 5])

In [92]:
y[:,1]

array([2, 7])

In [93]:
y[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [94]:
x

array([1, 2, 3, 4, 5])

In [95]:
x<2

array([ True, False, False, False, False])

In [99]:
(x<2) or (x>4)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [98]:
(x<2) | (x>4)

array([ True, False, False, False,  True])

In [100]:
mask = x < 3
mask

array([ True,  True, False, False, False])

In [101]:
x[mask]

array([1, 2])

In [105]:
np.sum(x<3)

2

In [106]:
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [108]:
x == y[0,]

array([ True,  True,  True,  True,  True])

In [109]:
x

array([1, 2, 3, 4, 5])

In [111]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(9,0,-1).reshape(3,3)
a1 < a2

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

slice

In [8]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [115]:
x[::2]

array([0, 2, 4, 6, 8])

In [116]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [117]:
x[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
y = np.arange(0,16).reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
y[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [14]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [16]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [17]:
x = np.arange(0,9)
y = x.reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
y.reshape(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
y.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
type(y)

numpy.ndarray

In [22]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
# reshaped = y.reshape(np.size(y))
# raveled = y.ravel()
# reshaped
# raveled
# reshaped[2] = 1000
# raveled[5] = 2000
# y

array([   0,    1, 1000,    3,    4, 2000,    6,    7,    8])

In [30]:
a = np.size(y)
a

9

In [32]:
b = y.reshape(9)
b

array([   0,    1, 1000,    3,    4, 2000,    6,    7,    8])

In [33]:
y

array([[   0,    1, 1000],
       [   3,    4, 2000],
       [   6,    7,    8]])

In [3]:
x = np.arange(0,9)
y = x.reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
reshaped = y.reshape(9)
reshaped

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
raveled = y.ravel()
raveled

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
raveled

2000

In [12]:
raveled = y.ravel()
raveled

array([   0,    1, 1000,    3,    4,    5,    6,    7,    8])

In [13]:
raveled[5] = 2000
y

array([[   0,    1, 1000],
       [   3,    4, 2000],
       [   6,    7,    8]])

In [14]:
y = np.arange(0,9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
flattened = y.flatten?

In [16]:
flattened = y.flatten()
flattened

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
flattened[0] = 1000
flattened

array([1000,    1,    2,    3,    4,    5,    6,    7,    8])

In [18]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
flattened.shape = (3,3)
flattened

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8]])

In [20]:
flattened.T

array([[1000,    3,    6],
       [   1,    4,    7],
       [   2,    5,    8]])

合并

In [21]:
a = np.arange(9).reshape(3,3)
b = (a + 1) * 10
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [1]:
b

NameError: name 'b' is not defined

In [2]:
import numpy as np

In [3]:
a = np.arange(9).reshape(3,3)
b = (a + 1) * 10
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
np.hstack((a,b))

array([[ 0,  1,  2, 10, 20, 30],
       [ 3,  4,  5, 40, 50, 60],
       [ 6,  7,  8, 70, 80, 90]])

In [8]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2, 10, 20, 30],
       [ 3,  4,  5, 40, 50, 60],
       [ 6,  7,  8, 70, 80, 90]])

In [11]:
np.dstack((a,b))

array([[[ 0, 10],
        [ 1, 20],
        [ 2, 30]],

       [[ 3, 40],
        [ 4, 50],
        [ 5, 60]],

       [[ 6, 70],
        [ 7, 80],
        [ 8, 90]]])

In [12]:
np.dstack?

In [13]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
one_d_a = np.arange(5)
one_d_b = (one_d_a + 1) * 10
np.column_stack((one_d_a,one_d_b))

array([[ 0, 10],
       [ 1, 20],
       [ 2, 30],
       [ 3, 40],
       [ 4, 50]])

In [17]:
np.row_stack((one_d_a,one_d_b))

array([[ 0,  1,  2,  3,  4],
       [10, 20, 30, 40, 50]])

matrix 加减乘，内积，外积

In [18]:
x = np.array([1,5,2])
y = np.array([7,4,1])
x + y

array([8, 9, 3])

In [19]:
x * y

array([ 7, 20,  2])

In [20]:
x - y

array([-6,  1,  1])

In [21]:
x / y

array([0.14285714, 1.25      , 2.        ])

In [22]:
x = np.array([1,2,3])
y = np.array([-7,8,9])
np.dot(x,y)

36

In [23]:
np.dot?

In [24]:
x = np.array([1,2,3])
y = np.array([1,1,1])
np.dot(x,y)

6

In [36]:
dot = np.dot(x,y)

x_modulus = np.sqrt((x*x).sum())
y_modulus = np.sqrt((y*y).sum())
cos_angle = dot / x_modulus / y_modulus
angle = np.arccos(cos_angle)
print("angle=",angle)


angle= 0.3875966866551805


In [37]:
print(angle * 360 / 2 /np.pi)
x_modulus * y_modulus * cos_angle

22.207654298596477


6.0

In [38]:
x = np.array(((2,3),(3,5)))
y = np.array(((1,2),(5,-1)))
print(x*y)

[[ 2  6]
 [15 -5]]


In [50]:
x = np.matrix(((2,4),(3,1)))
y= np.matrix(((1,2),(5,-1)))
x


matrix([[2, 4],
        [3, 1]])

In [52]:
y

matrix([[ 1,  2],
        [ 5, -1]])

In [53]:
x * y

matrix([[22,  0],
        [ 8,  5]])

In [46]:
x = np.array(((1,1),(2,3)))
y = np.array(((-1,-1),(0,0)))
x * y

array([[-1, -1],
       [ 0,  0]])

In [54]:
np.dot?

In [57]:
np.mat(x)

matrix([[2, 4],
        [3, 1]])

In [58]:
x

matrix([[2, 4],
        [3, 1]])

In [60]:
x = np.array([0,0,1])
y = np.array([0,1,0])
np.cross(x,y)

array([-1,  0,  0])

In [65]:
a = np.arange(1,10)
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [69]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [71]:
m = np.arange(10,19).reshape(3,3)
m

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [72]:
m.min()

10

In [73]:
m.max()

18

In [74]:
m.argmin()

0

In [77]:
m.argmax()

8

In [79]:
m.min(axis=0)

array([10, 11, 12])